### PR TITLE
fix(ElasticasSearchable): Set `liveIndex` when unpublishing a page

### PR DESCRIPTION
**Pull request by robbash**

### CODE REVIEW

**Comment by nyeholt** [comment]
Just to confirm the flow here, this flag gets set and then the Searchable::onBeforeDelete() call is triggered by the framework?

**Comment by nyeholt** [comment]
On that last comment - I can't see an explicit service->remove($item) call being made, so wanting to understand how that happens for the live document.

**Comment by robbash** [comment]
Yeah, you right with the first comment. And re. the 2nd, `Searchable::onBeforeDelete()` _is_ where the `remove` is called. I missed that in the stacktrace earlier, so might be good to shift setting `liveIndex=true` to the `onBeforeDelete` method.

**Comment by nyeholt** [comment]
Ah cool - so

* ElasticaSearchable::onBeforeUnpublish - sets liveIndex = true
* Searchable::onBeforeDelete() - calls ->remove()
* then call to $record->getElasticaDocument
* ElasticaSearchable::getElasticaDocument uses liveIndex to dictate the stage for the doc

Looks good then! Love short commits :)

**Pull request merged**
